on:
  push:
    branches:
      - default
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v2
      - run: dotnet build -c Release
      - run: dotnet test -c Release --no-build
